server:
  port: ${PORT:9093}
spring:
  application:
    name: video-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: videodb


eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: ${ADDRESS:127:0.0.1}
#    preferIpAddress: ${IPADDRESS:true}
    hostname: ${HOSTNAME:localhost}


management:
  endpoints:
    web:
      exposure:
        include: '*'

  info:
    env:
      enabled: true
info:
  app:
    name: 'video-service'
    description: 'This is the video service '
    version: 1.0




